---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : hooligan
production_url : 'http://blog.mlskill.com'

posts:
  permalink: /:categories/:title/
  summary_lines: 5
  latest: 10

pages:
  permalink: 'pretty'
