title : 热血hacker Loki
tagline: I was Borning to Make U Happy
author :
  name : Blood Loki 
  email : seven5272@gmail.com 
  github : sevendoors
  twitter : ProSe7en 
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
